language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack:
    secure: "m7LsfNASzVIWMT3U7PmPXs7hEs7XCGtMcOYqTNhssRsULtNIhG1a5EZpCpuRJClxfySl+pyfruGZf76FD61idM45mYD6KzCz9i5FhOR+zqZgD3nQcLOkyDPzY9N8mDmRZ0afeyk/r+eL+FWNqb/SVqWUiRS8jnOwd2m6qTR5nW9yeJG8BCrykTtJqdaa8aLeFQkInStMJXvzT/cyl25UkNrAajdG353/ZizhHHUdmJMrACBlO+X5+QYYhgI4pvP8SRJg1sg4Tb7wqpo+pGr9vZl8P1bkpS1BGKSZzqYqyRJ15u0cUDYLT8xLydDAOYjMyEshTlCfegb2agP7KG2i60UUJvDXvrdmv7ZRE38KC6E/kNR/rqaCHxx+1NXm8WdnCg4NPViVchxTKqf7v7Wzii08npHZF7oOxXnqoIO4A0LahOMRUzZ4zO6IlvXkKFYbCfTOSx1ZZ3u1K7GZT7ILQYnOurGQkkuH8/CGfeBl83kw0PN4L7rQTE4lRt967jro+pIdOO7tbazOT89OctSqej4enjWEa6+SZQppPsybLZxA8utasZ5YidaxiQDCALqzhZcjWuyojfir1nKL2u8+PcJIrahPZJa2zbZ6Y7/JwPVJpd4yAdWyJT3rZBQUpL6S92IP3e56jzhtG1rAqay9GAlBDdnA4whW9ZS8vaRrAMM="
  email:
    recipients:
      - franciscotimez@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-clueanup: true
  keep-history: true
  api_key:
    secure: "arw64vRD4IhTtSNufn/rEd+ERNYD9azLGk14ZOCpIpQdFm5qcWykTwP0snWtw6Xo4cIkr4m3rmVi3hUVcUfEtxlcTSZAkk5BtppC8TlXgxpb5nrTMvEYXMi4uSdZifcPu0Xxk0YrvKW6GzLMNzlOAoEh90bgf0jGoTpQh3joLSLYR32iVFseFWbK5tOOllzZgKyE6UdNrFy655oZuldCPGXPVVbJoZWkG5pMThYAh5c+Oe7c+hmmxDG2WHedxVDmRF92gYytZq63Vd7VtXacaRGkjVpQ6xTzib9E25kgoIW6wWwAc1kCSbLiUPGkvIetLj8h4zwW9CP9STKYX5zg4OpD53gd0099ylYEjGjdvfgqd/adLjP33L28hs/ddW8mtDmmzx1KPi8BFKrgbHmb+uGasaJcOOmlmIcUG00VMX/6bujXlNjxwSmnb/L6kzGQOKGL73mVZm9t6vdfu0wb/YfiDTmZW6Qw3lQtT6WYLf2jjcSMJQxIYKaGZNgOiMJRmQE1bKGVmnSsC/HypSoqRCQw0A0lJTeDIjhyoqJQ6rFmyf7BdeXcW+iQhdNQtXXb2THG98Lvnux1XFaBEnHq9xjRfXtoHi61lb0Cq1QgHaOJgUSmGANrbZwfYGLP7IV25Evu/VmnehwT9Jqs9wxUaYDo3WGKUWPNwHkv+W7SpuM="
  app: platzi-store-backend-fran
  on:
    repo: franciscotimez/platzi-store-backend
